#!/bin/sh

# .bash_profile ##############################################################

# User specific environment and startup programs

PATH=$PATH:$HOME/bin:/sbin:/usr/sbin:/usr/games/bin
MANPATH=$MANPATH:$HOME/share/man
PYTHONPATH="$HOME/lib/python2.5:/usr/local/lib64/python2.6:$PYTHONPATH"
XDG_CONFIG_HOME=~/.config
XDG_DATA_HOME=~/.local/share
BROWSER=firefox
EDITOR=vim
#OOO_FORCE_DESKTOP="gnome"

export PATH
export MANPATH
export PYTHONPATH
export XDG_CONFIG_HOME
export XDG_DATA_HOME
export BROWSER
export EDITOR
#export OOO_FORCE_DESKTOP

# .bashrc ####################################################################

#export XMODIFIERS="@im=gcin"
#export GTK_IM_MODULE="xim"
#export QT_IM_MODULE="xim"
#export XIM_PROGRAM="gcin"

# .xinitrc ###################################################################

xrdb -merge .Xresources
which $1 &> /dev/null
if [ "$?" != "0" ]; then
	exec startfluxbox
else
	exec $1
fi
